migrating circleci to github workflows
tophat/yvm pull request #884
Opened 2020-12-15 16:22 UTC by akeshk

## Description

### Checklist
- [ ] This PR has updated documentation
- [ ] This PR has sufficient testing

## DevQA

### DevQA Prep

- Please `make node_modules`, this PR uses a new package

### DevQA Steps

### Comments

2020-12-16 20:26 UTC, noahnu commented on .github/workflows/pull-request.yml
> +    runs-on: ubuntu-18.04
(nb) you could update this to `ubuntu-20.04`

2020-12-16 20:27 UTC, noahnu commented on .github/workflows/pull-request.yml
> +    runs-on: ubuntu-18.04
(nb) could update this to

2020-12-16 20:29 UTC, noahnu commented on .github/workflows/pull-request.yml
> +        run: yarn run semantic-release --dry-run
If we're using the github action, I'd just swap this out for the action in dry run mode.

2020-12-16 20:29 UTC, noahnu commented on .github/workflows/release.yml
> +          dry_run: false
You can test this by enabling the dry_run.

2020-12-16 20:31 UTC, noahnu commented on .github/workflows/release.yml
> +            @semantic-release/git
Use the `.releaserc.js` file as a reference. You're missing some plugins. If you have difficulty using the correct plugins, you can continue to just use `yarn semantic-release`

2020-12-16 20:32 UTC, noahnu commented on .github/workflows/release.yml
> +          BRANCH: gh-pages
You can test this by deploying to a custom test branch. E.g. `gh-pages-test` (just make the branch first)

2020-12-16 20:33 UTC, noahnu requested changes
Missing semantic release plugins

2020-12-16 20:33 UTC, noahnu commented on .github/workflows/release.yml
> +            @semantic-release/git
If you do get it to work with github actions, remove the releaserc file if it's no longer in use

2020-12-17 15:35 UTC, noahnu commented on .github/workflows/pull-request.yml
> +      - name: Installl yvm
```suggestion
      - name: Install yvm
```

2020-12-17 15:54 UTC, noahnu approved these changes
I'll merge

2020-12-17 15:57 UTC, merged

2020-12-17 17:32 UTC, noahnu commented
@all-contributors please add @akeshk for infrastructure, tools, and code

2020-12-17 17:34 UTC, noahnu commented
@all-contributors please add @noahnu for infrastructure

2020-12-18 14:19 UTC, iamogbz commented on .github/workflows/pull-request.yml
> +        run: make node_modules
Shouldn't this run regardless of a cache hit, that was happening in the previous circle config

2020-12-31 18:54 UTC, iamogbz commented
:tada: This PR is included in version 4.1.0 :tada:

The release is available on [GitHub release](https://github.com/tophat/yvm/releases/tag/v4.1.0)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: